--elimina los triggers
DROP TRIGGER IF EXISTS  bitacoraCO_Delete1
DROP TRIGGER IF EXISTS  bitacoraCO_Insert1
DROP TRIGGER IF EXISTS  bitacoraBeneficiario_Insert1
DROP TRIGGER IF EXISTS  bitacoraBeneficiario_Delete1
DROP TRIGGER IF EXISTS  bitacoraCO_Update1
DROP TRIGGER IF EXISTS  bitacoraBeneficiario_Update1

DELETE FROM Usuario
DELETE FROM Beneficiario
DELETE FROM MovCO
DELETE FROM MovCOInteres
DELETE FROM MovimientoCA
DELETE FROM EstadodeCuenta
DELETE FROM CuentaObjetivo
DELETE FROM CuentadeAhorro
DELETE FROM Persona
DELETE FROM Parentesco
DELETE FROM Evento
DELETE FROM TipoCuentaAhorro
DELETE FROM TipoDocIdentidad
DELETE FROM TipoMoneda
DELETE FROM TipoMovimientoCA
DELETE FROM TipoMovimientoCO
DELETE FROM TipoMovimientoCOI
DELETE FROM TipoEvento



DBCC CHECKIDENT (Usuario, RESEED, 0)
DBCC CHECKIDENT (Beneficiario, RESEED, 0)
DBCC CHECKIDENT (EstadodeCuenta, RESEED, 0)
DBCC CHECKIDENT (CuentadeAhorro, RESEED, 0)
DBCC CHECKIDENT (CuentaObjetivo, RESEED, 0)
DBCC CHECKIDENT (Persona, RESEED, 0)
DBCC CHECKIDENT (Parentesco, RESEED, 0)
DBCC CHECKIDENT (TipoCuentaAhorro, RESEED, 0)
DBCC CHECKIDENT (TipoDocIdentidad, RESEED, 0)
DBCC CHECKIDENT (TipoMoneda, RESEED, 0)
DBCC CHECKIDENT  (TipoMovimientoCA, RESEED, 0)
DBCC CHECKIDENT (TipoMovimientoCO, RESEED, 0)
DBCC CHECKIDENT (TipoMovimientoCOI, RESEED, 0)
DBCC CHECKIDENT  (MovimientoCA, RESEED, 0)
DBCC CHECKIDENT (MovCO, RESEED, 0)
DBCC CHECKIDENT (MovCOInteres, RESEED, 0)
DBCC CHECKIDENT (TipoEvento, RESEED, 0)
DBCC CHECKIDENT (Evento, RESEED, 0)
